# This rule is not used by the project resume-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to resume.joshuajebarj.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: resume-operator
    app.kubernetes.io/managed-by: kustomize
  name: resume-viewer-role
rules:
- apiGroups:
  - resume.joshuajebarj.com
  resources:
  - resumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resume.joshuajebarj.com
  resources:
  - resumes/status
  verbs:
  - get
