# This rule is not used by the project resume-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over resume.joshuajebarj.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: resume-operator
    app.kubernetes.io/managed-by: kustomize
  name: resume-admin-role
rules:
- apiGroups:
  - resume.joshuajebarj.com
  resources:
  - resumes
  verbs:
  - '*'
- apiGroups:
  - resume.joshuajebarj.com
  resources:
  - resumes/status
  verbs:
  - get
